spring:
  # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
  # 连接池配置
  datasource:
    url: jdbc:mysql://192.168.213.106:3306/store_admin?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: cache,mq
  thymeleaf:
    cache: true # 开启缓存
    check-template: true # 检查模板是否存在
    check-template-location: true # 检查模板位置正确性 默认查找 resources/templates 文件夹内
    servlet:
      content-type: text/html # 直接嵌入到html文件中
    enabled: true
    encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    type-aliases-package: com.uestc.pojo # 设置别名
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eager-load:
    enabled: true # 开启饥饿加载提升第一次访问速度
    clients:
      - store-service # 指定开启服务
feign:
  httpclient:
    enabled: true # 开启httpClient开关,启动连接池,提升Feign连接效率!
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单路径最大连接数
    client: # 默认3秒
      default: # 设置连接超时时间
        ConnectTimeout: 10000
        ReadTimeout: 10000 # 设置读取数据超时时间
server:
  servlet:
    context-path: /admin




